name: Download, Encode, and Upload

on:
  workflow_dispatch:
    inputs:
      input_file:
        description: "Input file name"
        required: true
      preset:
        description: "Preset to use when encoding"
        required: true
        default: '1080p'
        type: choice
        options:
          - 1080p
          - 1080p-animation
          - 4k
          - 4k-animation
      crf:
        description: "CRF value to use when encoding"
        required: true
        default: '20'
        type: string

jobs:
  encode-file:
    runs-on: ubuntu-latest

    env:
      BUCKET_NAME: ${{ vars.BUCKET_NAME }}
      ENDPOINT_URL: ${{ vars.ENDPOINT_URL }}
      ACCESS_KEY_ID: ${{ secrets.ACCESS_KEY_ID }}
      SECRET_ACCESS_KEY: ${{ secrets.SECRET_ACCESS_KEY }}

    steps:
    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id $ACCESS_KEY_ID
        aws configure set aws_secret_access_key $SECRET_ACCESS_KEY
        aws configure set default.region auto
        aws configure set default.s3.endpoint $ENDPOINT_URL

    - name: Download File
      run: |
        ls -l $HOME/.aws/config
        ls -l $HOME/.aws/credentials
        aws s3 ls s3://$BUCKET_NAME --endpoint-url $ENDPOINT_URL
        aws s3 ls s3://$BUCKET_NAME
        aws s3 cp s3://$BUCKET_NAME/${{ github.event.inputs.input_file }} ./

    - name: Encode File with Docker image
      run: |
        #docker run --rm -v "$(pwd)":/data davidmatthews/handbrake-cli ${{ github.event.inputs.input_file }} ${{ github.event.inputs.preset }} ${{ github.event.inputs.crf }}
        mv ${{ github.event.inputs.input_file }} renamed-${{ github.event.inputs.input_file }}

    - name: Upload Encoded File
      run: |
        rm ${{ github.event.inputs.input_file }}
        aws s3 cp ./* s3://$BUCKET_NAME/